CREATE DATABASE basic_login CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE basic_login;
CREATE TABLE users(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;